# Advent of Code Day 21

In [74]:
from utils import read_input
import numpy as np

In [132]:
def read_patterns():
    lines = read_input('Input/day21-example.txt')
    
    return lines
    
    
class GridPattern(object):
    
    def __init__(self, pattern, output):
        
        rows = np.asarray(list(p.split() for p in pattern.split('/')))
        
        print rows
        
        self.size = len(rows)     
        self.output = output
        
        self.permutations = []
        
        for side in xrange(0, 4):
            rotated = np.rot90(rows, k = side)
            flipped = np.flipud(rotated)
            
            self.permutations.append(rotated)
            self.permutations.append(flipped)           
      
              
    def display_permutations(self):
        
        for row_index in xrange(0, self.size):  
            perm_row = []
            for permutation in self.permutations:
                print permutation
                perm_row.append(permutation[row_index].tolist())                
                
            print '\t'.join(perm_row)
                
    
    def match(self, square):
        pass
    
    def replace(self, square):
        if not match(square):
            raise ValueError('Unable to replace within this square - pattern does not match')
            
        return output
    

In [133]:
patterns = read_patterns()

parts = patterns[0].split(' => ')
grid_pattern = GridPattern(parts[0], parts[1])

[['..']
 ['.#']]


In [134]:
grid_pattern.display_permutations()

[['..']
 ['.#']]
[['.#']
 ['..']]
[['..' '.#']]
[['..' '.#']]
[['.#']
 ['..']]
[['..']
 ['.#']]
[['.#' '..']]
[['.#' '..']]


TypeError: sequence item 0: expected string, list found

In [135]:
print grid_pattern.permutations

[array([['..'],
       ['.#']], 
      dtype='|S2'), array([['.#'],
       ['..']], 
      dtype='|S2'), array([['..', '.#']], 
      dtype='|S2'), array([['..', '.#']], 
      dtype='|S2'), array([['.#'],
       ['..']], 
      dtype='|S2'), array([['..'],
       ['.#']], 
      dtype='|S2'), array([['.#', '..']], 
      dtype='|S2'), array([['.#', '..']], 
      dtype='|S2')]


In [29]:
grid_pattern3 = GridPattern(patterns[1].split(' => ')[0], patterns[1].split(' => ')[1])

In [30]:
grid_pattern3.permutations

[['###', '..#', '.#.']]

In [31]:
grid_pattern3.display_pattern()

.#.
..#
###


In [73]:
gp = GridPattern('.#./..#/###', '#..#/..../..../#..#')

gp.display_permutations()

.#.	###	#..	..#
..#	..#	.#.	#..
###	.#.	###	###


In [75]:
n = np.asarray([[1, 2], [3, 4]])

In [76]:
n

array([[1, 2],
       [3, 4]])

In [77]:
n.rot90(k=1)

AttributeError: 'numpy.ndarray' object has no attribute 'rot90'

In [81]:
np.rot90(n, k=1)

array([[2, 4],
       [1, 3]])

In [82]:
np.flipud(n)

array([[3, 4],
       [1, 2]])

In [138]:
n = '../.#'

nn = n.split('/')

nnn = np.asarray([list(n2) for n2 in nn])

In [139]:
nnn

array([['.', '.'],
       ['.', '#']], 
      dtype='|S1')

In [140]:
nnn[0]

array(['.', '.'], 
      dtype='|S1')

In [141]:
np.rot90(nnn, k = 1)

array([['.', '#'],
       ['.', '.']], 
      dtype='|S1')

In [148]:
for k in xrange(0, 4):
    
    rd = np.rot90(nnn, k = k)
    print '/'.join(''.join(r) for r in rd)
    print np.flipud(rd)
    
    
    

../.#
[['.' '#']
 ['.' '.']]
.#/..
[['.' '.']
 ['.' '#']]
#./..
[['.' '.']
 ['#' '.']]
../#.
[['#' '.']
 ['.' '.']]


In [155]:
nnn[:, 1]

array(['.', '#'], 
      dtype='|S1')

In [154]:
nnn

array([['.', '.'],
       ['.', '#']], 
      dtype='|S1')